name: Conventional Commits

on:
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize

permissions: {}

jobs:
  validate_title:
    name: Validate PR title
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      pull-requests: read

    steps:
      - name: Check Conventional Commit format
        uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          types: |
            build
            chore
            ci
            docs
            feat
            fix
            perf
            refactor
            revert
            style
            test
